style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/c4mbr0nn3/podcats
options:
  tag_filter_pattern: "^v"
  commits:
    filters:
      Type:
        - feat
        - hotfix
        - fix
        - refactor
  commit_groups:
    sort_by: Custom
    title_order:
      - feat
      - hotfix
      - fix
      - refactor
    title_maps:
      feat: Features
      hotfix: Hot Fixes
      fix: Bug Fixes
      refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
